sonar.projectKey=dddaavo_dapp-bolsa-de-jugadores
sonar.organization=dappgrupom
sonar.java.source=21
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/config/**,**/generated-sources/**,**/auth/api/**,**/catalog/api/**,**/shared/error/**,**/DataInitializer.java,**/BolsaApplication.java
sonar.coverage.exclusions=**/config/**,**/auth/api/**,**/catalog/api/**,**/shared/error/**,**/DataInitializer.java,**/BolsaApplication.java,**/WhoScoredPlaywrightScraper.java
sonar.test.exclusions=**/*IT.java
